import SectionBanner from "@/components/ui/SectionBanner";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Corporate Banking | TabEdge",
  description: "Generated by create next app",
};

const CorporateBanking = () => {
  return (
    <div>
      <SectionBanner
        heading="Corporate Banking"
        description="Take control of your finances with a personal bank account from TabEdge Bank"
        className="text-white "
        backgroundImagePath="/assets/background/blue-gradiant.png"
      />
    </div>
  );
};

export default CorporateBanking;
