import ContactUs from "@/components/ContactUs/ContactUs";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Contact | TabEdge",
  description: "Generated by create next app",
};

const ContactPage = () => {
  return (
    <div>
      <ContactUs />
    </div>
  );
};

export default ContactPage;
