import BankControl from "@/components/shared/BankControl";
import SectionBanner from "@/components/ui/SectionBanner";
import IncludedPersonalBank from "@/components/PersonalBanking/IncludedPersonalBank";
import OnlineBanking from "@/components/PersonalBanking/OnlineBanking";
import PurchasingPower from "@/components/PersonalBanking/PurchasingPower";
import React from "react";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Personal Banking | TabEdge",
  description: "Generated by create next app",
};

const PersonalBanking = () => {
  return (
    <div>
      <SectionBanner
        heading="Personal Banking"
        description="Take control of your finances with a personal bank account from TabEdge Bank "
        className="text-white "
        backgroundImagePath="/assets/background/blue-gradiant.png"
      />
      <BankControl />
      <PurchasingPower />
      <OnlineBanking />
      <IncludedPersonalBank />
    </div>
  );
};

export default PersonalBanking;
