import SectionBanner from "@/components/ui/SectionBanner";
import AboutBussinessBanking from "@/components/BusinessBanking/AboutBussinessBanking";
import BussinessBankControl from "@/components/BusinessBanking/BusinessBankControl";
import Documents from "@/components/BusinessBanking/Documents";
import IncluedBusinessBanking from "@/components/BusinessBanking/IncluedBusinessBanking";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Business Banking | TabEdge",
  description: "Generated by create next app",
};

const BussinessBanking = () => {
  return (
    <>
      <SectionBanner
        heading="Business Banking"
        description="Open a U.S. business bank online. No need to be a U.S. registered company, citizen or residen"
        className="text-white "
        backgroundImagePath="/background/blue-gradiant.png"
      />
      <BussinessBankControl />
      <AboutBussinessBanking />
      <IncluedBusinessBanking />
      <Documents />
    </>
  );
};

export default BussinessBanking;
